
:toc:
:toc-placement: macro



= animate-earth
Dan Delany <dan.delany@gmail.com>

toc::[]

= Overview
This repository is an experiment in applying optical-flow-based motion interpolation to pre-processed RGB satellite imagery from Himawari-8's AHI imager, with the aim of regularly producing high-quality smoothed videos from these images, and sharing them with the world. https://www.youtube.com/channel/UC6Mlo4zfmEITcNoCpBKfEfg/playlists[The final products can be found on this Youtube channel], updated nearly daily.

== Acknowledgements
I didn't invent any of this stuff, I'm just putting the pieces together. The images come from the JMA's http://www.jma-net.go.jp/msc/en/support/index.html[Himawari-8] satellite, processed to true color by Steve Miller and Dan Lindsey at http://rammb.cira.colostate.edu/ramsdis/online/himawari-8.asp[NOAA/CIRA/RAMMB(/CSU/NESDIS/USA...)]. Motion interpolation is accomplished with the open source https://github.com/dthpham/butterflow)[Butterflow tool by dthpham], which uses http://docs.opencv.org/master/d7/d8b/tutorial_py_lucas_kanade.html#gsc.tab=0[OpenCV's implementation] of an http://www.diva-portal.org/smash/get/diva2:273847/FULLTEXT01.pdf[algorithm devised by Gunnar Farnebäck].

== Purpose
The primary purpose of this project is to share the awe-inspiring images of Earth created by the Himawari-8 AHI and the NOAA/CIRA/RAMMB team; thusly, these videos are optimized for aesthetic beauty rather than scientific utility. However, it also aims to encourage discussion and experimentation around the wider use of motion interpolation in scientific visualization and image processing.

== Process
The overall process implemented by these scripts is essentially:

. *scrape.js* - Retrieves new high-resolution true color Himawari-8 images from the http://rammb.cira.colostate.edu/ramsdis/online/himawari-8.asp[CSU/RAMMB webpage] and saves them locally.
. *main.js* - The main image processing pipeline, which does the following:
.. Splits the list of images into day-long sessions.
.. Makes cropped copies of the full-sized images for different regions & sessions.
.. Combines the cropped images into low-framerate video files.
.. Parses image timestamps to identify gaps between images that are > the expected 10 minute interval.
.. Generates and runs a command for Butterflow to produce a high-framerate, motion-interpolated video which corrects for imaging gaps by interpolating additional frames.
.. Compresses and saves the video as a local .mp4 file.
. *youtube.js* - Automatically updates the project's Youtube channel by creating playlists for each product and uploading newly created videos via the Youtube Data API.

= Butterflow
The project's main dependency is Butterflow

Butterflow supports Mac OS X, Ubuntu 15.04 (Vivid Vervet), Debian 8.2 (Jessie), and Arch Linux

== Mac OS X
The current version of Butterflow seems to be most stable/reliable and easiest to set up on OS X, if you have a https://support.apple.com/en-us/HT202823[recent Mac computer that supports OpenCL]. An older version can be installed https://github.com/dthpham/butterflow#os-x[with Homebrew + this one-liner] - *however, at the time of writing, the published version of butterflow on Homebrew contains a https://github.com/dthpham/butterflow/issues/13[bug which results in uninterpolated gaps between video segments].* For this reason, I recommend that you install it from a more recent version of the source, *unless* you plan to just use butterflow without these scripts, for simple interpolation of videos without any missing frames to account for.

https://github.com/dthpham/butterflow/wiki/Install-From-Source-Guide#os-x[To install from source on OS X, just follow these instructions.] You will need to http://brew.sh/[install Homebrew first] if you don't already have it. Note that the last few commands in that list must be re-entered any time you open a new terminal session or reboot, in order to use the source version instead of the global version:

```
cd butterflow
source bin/activate
echo "$(brew --prefix)/lib/python2.7/site-packages" > lib/python2.7/site-packages/butterflow.pth
python setup.py develop
```

== Ubuntu Linux
I have also gotten Butterflow running on Ubuntu 15.04. You may have issues installing it on versions older than this


== Dependencies
